name: status

on:
  workflow_run:
    workflows: ["email testing"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to Slack
        id: slack
        uses: act10ns/slack@v3
        with:
          status: success
          message: "Build Started! :rocket:"
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Update Slack Message - Running
        id: update-slack
        uses: act10ns/slack@v3
        with:
          status: running
          message: "Build in progress... :construction_worker:"
          update-ts: ${{ steps.slack.outputs.ts }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Update Slack Message - Failed
        id: update-slack-failed
        uses: act10ns/slack@v3
        with:
          status: failure
          message: "Build failed! :x:"
          update-ts: ${{ steps.update-slack.outputs.ts }}  # Corrected reference
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
s